
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftORleftANDrightNOTleftIGUALACIONDISTINTOleftMENORQMAYORQMAYORIGMENORIGleftMASMENOSCOMAleftMULDIVMODleftPARENIPARENDleftPOTrightUNARIOAND CADENA COMA CORD CORI DECIMAL DISTINTO DIV DOSPTS ENTERO ID IGUAL IGUALACION LLAVED LLAVEI MAS MAYORIG MAYORQ MENORIG MENORQ MENOS MOD MUL NOT OR PAREND PARENI POT PT PTCOMA RCONSOLE RLOG\n            inicio : sentencias\n        \n            sentencias : sentencias sentencia \n                      | sentencia\n        \n            sentencia : print PTCOMA\n        \n            print : RCONSOLE PT RLOG PARENI expresion PAREND\n        \n            expresion : expresion MAS expresion\n        \n            expresion : expresion MENOS expresion\n        \n            expresion : expresion MUL expresion\n        \n            expresion : expresion DIV expresion\n        \n            expresion : MENOS expresion %prec UNARIO\n        \n            expresion : PARENI expresion PAREND\n        \n            expresion : ENTERO\n                    | DECIMAL\n        expresion : CADENA'
    
_lr_action_items = {'RCONSOLE':([0,2,3,6,7,],[5,5,-3,-2,-4,]),'$end':([1,2,3,6,7,],[0,-1,-3,-2,-4,]),'PTCOMA':([4,18,],[7,-5,]),'PT':([5,],[8,]),'RLOG':([8,],[9,]),'PARENI':([9,10,11,13,19,20,21,22,],[10,11,11,11,11,11,11,11,]),'MENOS':([10,11,12,13,14,15,16,17,19,20,21,22,23,24,25,26,27,28,],[13,13,20,13,-12,-13,-14,20,13,13,13,13,-10,-11,-6,-7,-8,-9,]),'ENTERO':([10,11,13,19,20,21,22,],[14,14,14,14,14,14,14,]),'DECIMAL':([10,11,13,19,20,21,22,],[15,15,15,15,15,15,15,]),'CADENA':([10,11,13,19,20,21,22,],[16,16,16,16,16,16,16,]),'PAREND':([12,14,15,16,17,23,24,25,26,27,28,],[18,-12,-13,-14,24,-10,-11,-6,-7,-8,-9,]),'MAS':([12,14,15,16,17,23,24,25,26,27,28,],[19,-12,-13,-14,19,-10,-11,-6,-7,-8,-9,]),'MUL':([12,14,15,16,17,23,24,25,26,27,28,],[21,-12,-13,-14,21,-10,-11,21,21,-8,-9,]),'DIV':([12,14,15,16,17,23,24,25,26,27,28,],[22,-12,-13,-14,22,-10,-11,22,22,-8,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'inicio':([0,],[1,]),'sentencias':([0,],[2,]),'sentencia':([0,2,],[3,6,]),'print':([0,2,],[4,4,]),'expresion':([10,11,13,19,20,21,22,],[12,17,23,25,26,27,28,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> inicio","S'",1,None,None,None),
  ('inicio -> sentencias','inicio',1,'p_INICIO','Analizador.py',218),
  ('sentencias -> sentencias sentencia','sentencias',2,'p_SENTENCIAS','Analizador.py',226),
  ('sentencias -> sentencia','sentencias',1,'p_SENTENCIAS','Analizador.py',227),
  ('sentencia -> print PTCOMA','sentencia',2,'p_SENTENCIAS_PRINT','Analizador.py',238),
  ('print -> RCONSOLE PT RLOG PARENI expresion PAREND','print',6,'p_PRINT_SIMPLE','Analizador.py',247),
  ('expresion -> expresion MAS expresion','expresion',3,'p_EXPRESION_SUMA','Analizador.py',254),
  ('expresion -> expresion MENOS expresion','expresion',3,'p_EXPRESION_RESTA','Analizador.py',261),
  ('expresion -> expresion MUL expresion','expresion',3,'p_EXPRESION_MULTIPLICACION','Analizador.py',268),
  ('expresion -> expresion DIV expresion','expresion',3,'p_EXPRESION_DIVISION','Analizador.py',275),
  ('expresion -> MENOS expresion','expresion',2,'p_EXPRESION_UNARIO','Analizador.py',282),
  ('expresion -> PARENI expresion PAREND','expresion',3,'p_EXPRESION_PARENTESIS','Analizador.py',289),
  ('expresion -> ENTERO','expresion',1,'p_EXPRESION_NUMBER','Analizador.py',296),
  ('expresion -> DECIMAL','expresion',1,'p_EXPRESION_NUMBER','Analizador.py',297),
  ('expresion -> CADENA','expresion',1,'p_EXPRESION_CADENA','Analizador.py',302),
]
